"use client";
import Link from "next/link";
import { useState } from "react";
type PlanCode = "basic_1m"|"basic_3m"|"basic_6m"|"pro_1m"|"pro_3m"|"pro_6m";
type Props = { isYookassaEnabled: boolean; canUseFreeTrial: boolean; isFreeTrialEnabled: boolean };
const plans = [
  { code:"basic_1m", tier:"BASIC", price:"299 ₽", term:"1 месяц", discount:"" }, { code:"basic_3m", tier:"BASIC", price:"807 ₽", term:"3 месяца", discount:"−10%" }, { code:"basic_6m", tier:"BASIC", price:"1 345 ₽", term:"6 месяцев", discount:"−25%" },
  { code:"pro_1m", tier:"PRO", price:"799 ₽", term:"1 месяц", discount:"" }, { code:"pro_3m", tier:"PRO", price:"2 157 ₽", term:"3 месяца", discount:"−10%" }, { code:"pro_6m", tier:"PRO", price:"3 596 ₽", term:"6 месяцев", discount:"−25%" },
] as const;
export default function BuyBasicButton({isYookassaEnabled,canUseFreeTrial,isFreeTrialEnabled}: Props) {
 const [loading,setLoading]=useState<PlanCode|"trial"|null>(null); const [error,setError]=useState("");
 async function buy(planCode:PlanCode) { try { setLoading(planCode); setError(""); const res=await fetch("/api/payments/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planCode})}); const data=await res.json(); if(!res.ok) throw new Error(data?.error||"Не удалось создать платёж"); if(!data?.redirectUrl) throw new Error("Сервис оплаты не вернул ссылку для перехода"); window.location.href=data.redirectUrl; } catch(e) { setError(e instanceof Error?e.message:"Ошибка сети"); } finally { setLoading(null); } }
 async function trial() { try {setLoading("trial");setError("");const r=await fetch("/api/subscription/free-trial",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Не удалось активировать пробный доступ");window.location.href=d.redirectUrl||"/dashboard";}catch(e){setError(e instanceof Error?e.message:"Ошибка сети")}finally{setLoading(null)} }
 return <div className="space-y-6"><div className="rounded-2xl border border-blue-300/35 bg-blue-400/10 p-4"><div className="text-lg font-extrabold text-blue-100">Pro — автоматизация продвижения</div><p className="mt-1 text-sm leading-6 text-white/70">Включает всё из Basic, бид-менеджер Авито и до 10 стратегий на аккаунт.</p></div><div className="grid gap-4 md:grid-cols-3">{plans.map(plan=><button key={plan.code} type="button" onClick={()=>buy(plan.code)} disabled={loading!==null} className={`rounded-2xl border p-5 text-left transition hover:-translate-y-1 disabled:opacity-60 ${plan.tier==="PRO"?"border-blue-300/45 bg-blue-400/15 hover:bg-blue-400/25":"border-white/20 bg-white/10 hover:bg-white/15"}`}><div className="flex items-center justify-between gap-2"><span className="text-sm font-extrabold tracking-wide text-white/80">{plan.tier}</span>{plan.discount&&<span className="rounded-full bg-yellow-300 px-2 py-1 text-[10px] font-extrabold text-black">{plan.discount}</span>}</div><div className="mt-3 text-2xl font-extrabold">{plan.price}</div><div className="mt-1 text-sm text-white/75">{plan.term}</div><div className="mt-4 rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">{loading===plan.code?"Переход к оплате…":isYookassaEnabled?"Оплатить":"Активировать"}</div></button>)}</div><div className="flex flex-wrap gap-3">{isFreeTrialEnabled&&canUseFreeTrial&&<button type="button" onClick={trial} disabled={loading!==null} className="btn-secondary disabled:opacity-60">{loading==="trial"?"Активация…":"Попробовать Basic 1 день бесплатно"}</button>}<Link href="/dashboard" className="btn-secondary">В кабинет</Link></div>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}</div>;
}